import { i18n } from '../i18n';
import { showMessage } from '../state/messageStore';
import { handleImportResponse } from '../tools/import-mesh/importFlow';

/** Example scans generated by scripts/generate-examples.py into resources/examples. */
export const EXAMPLES = ['bracket', 'flange', 'knob'] as const;
export type ExampleId = (typeof EXAMPLES)[number];

/** Load a bundled example scan into the import panel, like a file chosen in the dialog. */
export async function openExample(example: ExampleId = 'bracket'): Promise<void> {
  const response = await window.m2c.files.run(
    'openExample',
    { exampleId: example },
    { title: i18n.t(`help:examples.${example}`), filterName: 'STL' },
  );
  // Without a dialog, "canceled" means the example file is not installed.
  if ('canceled' in response) {
    showMessage('error', i18n.t('help:examples.missing', { file: `${example}.stl` }));
    return;
  }
  handleImportResponse(response);
}
