"""Codes of the solid modelling operations (Open CASCADE)."""

from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_RESULT = "cad.invalidResult"
    OCCT_UNAVAILABLE = "cad.occtUnavailable"
    PROFILE_OPEN = "cad.profileOpen"
    """The sketch has no closed profile to extrude or revolve."""
    LOOP_NOT_FOUND = "cad.loopNotFound"
    """A selected profile loop no longer exists in the sketch."""
    ZERO_LENGTH = "cad.zeroLength"
    """Extrusion distances or revolve angle give no volume."""
    AXIS_CROSSES_PROFILE = "cad.axisCrossesProfile"
    AXIS_NOT_IN_PLANE = "cad.axisNotInPlane"
    AXIS_NOT_FOUND = "cad.axisNotFound"
    """The sketch line or feature chosen as axis provides no axis."""
    PLANE_PARALLEL = "cad.planeParallel"
    """The up-to plane of an extrusion is parallel to the extrusion direction."""
    PLANE_BEHIND = "cad.planeBehind"
    SYMMETRIC_TO_PLANE = "cad.symmetricToPlane"
    """A symmetric extrusion cannot end at one plane."""
    NOT_A_PLANE = "cad.notAPlane"
    NOT_A_PATCH = "cad.notAPatch"
    EMPTY_RESULT = "cad.emptyResult"
    """Cut or intersection removes the whole body."""
    NO_OVERLAP = "cad.noOverlap"
    """The bodies of a boolean do not touch, so the operation changes nothing."""
    MULTIPLE_SOLIDS = "cad.multipleSolids"
    """The result falls apart into several solids."""
    BOOLEAN_FAILED = "cad.booleanFailed"
    TOOL_MISSES_BODY = "cad.toolMissesBody"
    """The splitting plane or patch does not cut the body."""
    FILLET_FAILED = "cad.filletFailed"
    CHAMFER_FAILED = "cad.chamferFailed"
    EDGE_NOT_FOUND = "cad.edgeNotFound"
    NO_EDGES = "cad.noEdges"
    TARGET_REQUIRED = "cad.targetRequired"
    TOOLS_REQUIRED = "cad.toolsRequired"
    TOOL_IS_TARGET = "cad.toolIsTarget"
    UNSUPPORTED_FIT = "cad.unsupportedFit"
    """A primitive body needs a cylinder, cone, sphere or torus fit."""
    NO_EXTENT = "cad.noExtent"
    """The fit has no scan triangles to derive the body extent from."""
    TRIM_NEEDS_SURFACE = "cad.trimNeedsSurface"
    """Trimming needs at least one body or surface besides planes."""
    NO_CLOSED_REGION = "cad.noClosedRegion"
    """The trim inputs enclose no region (a surface does not reach past the others)."""
    NO_PIECE_KEPT = "cad.noPieceKept"
    """Every piece of a trim was removed."""


class IssueCode(StrEnum):
    HIGH_TOLERANCE = "cad.highTolerance"
    SPLIT_FACES_KEPT = "cad.splitFacesKept"
    FILLET_NARROWED = "cad.filletNarrowed"
    """Where the faces bend tighter than the radius, the fillet narrows (to `smallest`)."""


class ProgressStage(StrEnum):
    TESSELLATING = "cad.tessellating"
    MODELLING = "cad.modelling"
    BOOLEAN = "cad.boolean"
    FILLET = "cad.fillet"
